# Generated by Django 6.0.7 on 2026-07-10 08:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conducteurs', '0001_initial'),
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PleinCarburant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date_plein', models.DateTimeField(default=django.utils.timezone.now)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometrage_au_plein', models.PositiveIntegerField()),
                ('station', models.CharField(blank=True, max_length=150)),
                ('conducteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pleins_carburant', to='conducteurs.conducteur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pleins_carburant', to='vehicules.vehicule')),
            ],
            options={
                'ordering': ['-date_plein'],
                'indexes': [models.Index(fields=['vehicule', 'date_plein'], name='carburant_p_vehicul_30333b_idx')],
            },
        ),
    ]
