# Generated by Django 6.0.7 on 2026-07-10 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('type_maintenance', models.CharField(choices=[('preventive', 'Préventive (planifiée)'), ('curative', 'Curative (panne)')], max_length=20)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('description', models.TextField()),
                ('date_intervention', models.DateField()),
                ('kilometrage_intervention', models.PositiveIntegerField()),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prestataire', models.CharField(blank=True, max_length=150)),
                ('prochaine_echeance_date', models.DateField(blank=True, null=True)),
                ('prochaine_echeance_km', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='vehicules.vehicule')),
            ],
            options={
                'ordering': ['-date_intervention'],
                'indexes': [models.Index(fields=['vehicule', 'date_intervention'], name='maintenance_vehicul_e36889_idx')],
            },
        ),
    ]
