# Generated by Django 6.0.7 on 2026-07-10 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('numero_permis', models.CharField(max_length=50, unique=True)),
                ('categorie_permis', models.CharField(choices=[('A', 'A — Moto'), ('B', 'B — Véhicule léger'), ('C', 'C — Poids lourd'), ('D', 'D — Transport en commun'), ('EB', 'EB — Remorque')], max_length=5)),
                ('date_expiration_permis', models.DateField()),
                ('date_embauche', models.DateField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_mission', 'En mission'), ('en_conge', 'En congé'), ('suspendu', 'Suspendu')], db_index=True, default='disponible', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='conducteurs/photos/')),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
