# Generated by Django 6.0.7 on 2026-07-10 08:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conducteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('immatriculation', models.CharField(db_index=True, max_length=20, unique=True)),
                ('numero_chassis', models.CharField(max_length=50, unique=True)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('annee', models.PositiveIntegerField()),
                ('type_vehicule', models.CharField(choices=[('berline', 'Berline'), ('suv', 'SUV'), ('utilitaire', 'Utilitaire'), ('camion', 'Camion'), ('moto', 'Moto'), ('bus', 'Bus / Minibus')], max_length=20)),
                ('type_carburant', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride'), ('electrique', 'Électrique')], max_length=20)),
                ('cylindree_cm3', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_places', models.PositiveSmallIntegerField(default=5)),
                ('caracteristiques', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('en_service', 'En service'), ('en_maintenance', 'En maintenance'), ('en_panne', 'En panne'), ('hors_service', 'Hors service'), ('vendu', 'Vendu / réformé')], db_index=True, default='en_service', max_length=20)),
                ('kilometrage_actuel', models.PositiveIntegerField(default=0)),
                ('site_affectation', models.CharField(blank=True, max_length=100)),
                ('date_acquisition', models.DateField()),
                ('prix_acquisition', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valeur_actuelle_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicules/photos/')),
            ],
            options={
                'ordering': ['immatriculation'],
                'indexes': [models.Index(fields=['statut', 'is_active'], name='vehicules_v_statut_83b1e1_idx'), models.Index(fields=['type_vehicule'], name='vehicules_v_type_ve_43ab0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='conducteurs.conducteur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='vehicules.vehicule')),
            ],
            options={
                'ordering': ['-date_debut'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('date_fin__isnull', True)), fields=('vehicule',), name='un_seul_conducteur_actif_par_vehicule')],
            },
        ),
    ]
