# Generated by Django 6.0.7 on 2026-07-10 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('type_document', models.CharField(choices=[('assurance', 'Assurance'), ('visite_technique', 'Visite technique'), ('carte_grise', 'Carte grise'), ('vignette', 'Vignette'), ('autre', 'Autre')], max_length=30)),
                ('numero_document', models.CharField(blank=True, max_length=100)),
                ('date_emission', models.DateField()),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='vehicules/documents/')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicules.vehicule')),
            ],
            options={
                'ordering': ['date_expiration'],
                'indexes': [models.Index(fields=['date_expiration'], name='documents_d_date_ex_5f2abd_idx')],
            },
        ),
    ]
